name: Main
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d package &> /dev/null || echo package branch not found
        git subtree split -P "$PKG_ROOT" -b package
        git checkout package
        git commit -am "Fix samples folder"
        git push -f -u origin package
      env:
        PKG_ROOT: Assets/ffmpeg-clipper
