name: PackageSplitter
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split upm branch (force)
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split package branch
      run: |
        git branch -d package &> /dev/null || echo upm package not found
        git subtree split -P "$PKG_ROOT" -b package
        git push -f -u origin package
      env:
        PKG_ROOT: Assets/ffmpeg-clipper
